package Core;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;

public class ServerWorkerThread implements Runnable{
	Socket connectionSocket;//Socket generated by TCP
	
	//Constructor
	public ServerWorkerThread(Socket connectionSocket) throws IOException {
		if(connectionSocket!=null) {
			this.connectionSocket = connectionSocket;
		}else {
			throw new IOException("IOExcepion: Assigned connection socket "
														+ "doesn't exist.");
		}
	}
	
	@Override
	public void run() {
		try {
			InputStreamReader InputFromClient = new InputStreamReader(
											connectionSocket.getInputStream());
			BufferedReader connectionInStream = new BufferedReader(InputFromClient);
			String handShakeReq = connectionInStream.readLine();
			//Encapsulate handshake message
			HandShakeMessage hsm = new HandShakeMessage(handShakeReq);
			//If handshake field doesn't pass, close the connection
			if(!hsm.permitToConnect()) {
				connectionSocket.close();
				throw new IOException("Not Authorized: Server closed the connection.");
			}
			//Create output stream for response
			OutputStream output = connectionSocket.getOutputStream();
			DataOutputStream writeToClientStream = new DataOutputStream(output);
			//Write back actual message
			writeToClientStream.writeBytes("ACTUAL MESSAGE");
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				connectionSocket.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
}
